# Generated by Django 3.0.2 on 2020-11-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('rated', models.CharField(blank=True, max_length=10)),
                ('released', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('director', models.CharField(blank=True, max_length=100)),
                ('writer', models.CharField(blank=True, max_length=1000)),
                ('actors', models.CharField(blank=True, max_length=5000)),
                ('plot', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('awards', models.CharField(blank=True, max_length=200)),
                ('poster', models.CharField(blank=True, max_length=200)),
                ('metascore', models.IntegerField(blank=True, null=True)),
                ('imdbrating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('imdbvotes', models.IntegerField(blank=True, null=True)),
                ('imdbid', models.CharField(blank=True, max_length=20)),
                ('type_picture', models.CharField(blank=True, max_length=20, verbose_name='type')),
            ],
        ),
    ]
