# Generated by Django 3.0.2 on 2020-11-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rest_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='boxoffice',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='dvd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='totalseasons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
